name: corp_tale
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_easy_animations: ^0.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.3
  video_player: ^2.6.1
  path_provider: ^2.0.13
  image_picker: ^1.1.0
  permission_handler: ^11.3.1
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  firebase_messaging: ^15.0.2
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/country_code.json
    - assets/video.png
    - assets/images/
    - assets/icons/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
