// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xyi3yaV42SMiZPMELqdtptuCn3mv0iM',
    appId: '1:156913003494:web:2d9090851da027b043c427',
    messagingSenderId: '156913003494',
    projectId: 'videohosting-da5eb',
    authDomain: 'videohosting-da5eb.firebaseapp.com',
    storageBucket: 'videohosting-da5eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWcoRH93-U6Q27I449B3dXp1Nvl5aeng',
    appId: '1:156913003494:android:5c5349fdb098c51f43c427',
    messagingSenderId: '156913003494',
    projectId: 'videohosting-da5eb',
    storageBucket: 'videohosting-da5eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXr2aslyZjPKPJWzcOZiGz5FuaDJg1GJw',
    appId: '1:156913003494:ios:2de850ba0c51a62143c427',
    messagingSenderId: '156913003494',
    projectId: 'videohosting-da5eb',
    storageBucket: 'videohosting-da5eb.appspot.com',
    iosBundleId: 'com.example.videoHostingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXr2aslyZjPKPJWzcOZiGz5FuaDJg1GJw',
    appId: '1:156913003494:ios:2de850ba0c51a62143c427',
    messagingSenderId: '156913003494',
    projectId: 'videohosting-da5eb',
    storageBucket: 'videohosting-da5eb.appspot.com',
    iosBundleId: 'com.example.videoHostingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xyi3yaV42SMiZPMELqdtptuCn3mv0iM',
    appId: '1:156913003494:web:3a0c55d938a9d60443c427',
    messagingSenderId: '156913003494',
    projectId: 'videohosting-da5eb',
    authDomain: 'videohosting-da5eb.firebaseapp.com',
    storageBucket: 'videohosting-da5eb.appspot.com',
  );
}
